import React from 'react';
import { ArrowLeft, ShieldCheck, Activity, MessageSquare } from 'lucide-react';

export const SupportPage: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <button onClick={onBack} className="flex items-center gap-2 text-gray-500 hover:text-blue-600 mb-8 transition-colors">
        <ArrowLeft className="w-4 h-4" /> Back to Home
      </button>

      <div className="text-center mb-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-4">Support Center</h1>
        <p className="text-lg text-slate-600">How can we help you today?</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <div className="bg-blue-100 w-10 h-10 rounded-lg flex items-center justify-center mb-4 text-blue-600">
                <ShieldCheck className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold mb-2">What is VeriCite?</h3>
            <p className="text-slate-600">
                VeriCite Academic is a specialized tool designed to detect "hallucinated" citations—fake sources often generated by AI writing tools. We cross-reference your text against real academic databases like Crossref and Google Scholar to ensure every source is legitimate.
            </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
            <div className="bg-green-100 w-10 h-10 rounded-lg flex items-center justify-center mb-4 text-green-600">
                <Activity className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold mb-2">How it Works</h3>
            <p className="text-slate-600">
                Simply paste your text or upload a document. Our system uses advanced NLP to extract citations, then queries metadata repositories in real-time. We assign a "Trust Score" to your document based on the percentage of verified sources.
            </p>
        </div>
      </div>

      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8 mb-12">
          <h2 className="text-2xl font-bold mb-6">Interpreting Your Results</h2>
          <div className="space-y-4">
              <div className="flex gap-4">
                  <span className="w-32 flex-shrink-0 font-bold text-emerald-600">VERIFIED</span>
                  <p className="text-slate-600">The source was found in a trusted academic database (Crossref) or verified via Google Search grounding. The DOI or URL is valid.</p>
              </div>
              <div className="flex gap-4">
                  <span className="w-40 flex-shrink-0 font-bold text-rose-600">LIKELY FABRICATED</span>
                  <p className="text-slate-600">We could not find any evidence that this source exists in any academic repository. It is likely a fabrication by an AI model.</p>
              </div>
              <div className="flex gap-4">
                  <span className="w-32 flex-shrink-0 font-bold text-amber-600">AMBIGUOUS</span>
                  <p className="text-slate-600">We found partial matches (e.g., correct author but wrong year). Manual review is recommended.</p>
              </div>
          </div>
      </div>

      <div className="bg-slate-50 rounded-xl p-8 text-center border border-slate-200">
          <div className="inline-block p-3 bg-white rounded-full shadow-sm mb-4">
              <MessageSquare className="w-6 h-6 text-slate-700" />
          </div>
          <h2 className="text-xl font-bold mb-2">Need assistance?</h2>
          <p className="text-slate-600 mb-4">Support contact will be provided through the platform.</p>
      </div>
    </div>
  );
};