import React from 'react';
import { ArrowLeft } from 'lucide-react';

export const AcademicIntegrity: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-6 bg-white shadow-sm my-8 rounded-lg">
      <button onClick={onBack} className="flex items-center gap-2 text-gray-500 hover:text-blue-600 mb-8 transition-colors">
        <ArrowLeft className="w-4 h-4" /> Back
      </button>
      
      <h1 className="text-3xl font-bold mb-8 text-slate-900">Academic Integrity Guidelines</h1>
      
      <div className="prose prose-slate max-w-none text-slate-700 space-y-6">
        <p className="text-lg font-medium">VeriCite Academic is designed to support, not replace, the scholarly process.</p>
        
        <section>
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Our Mission</h2>
          <p>Our goal is to help students, researchers, and academics identify potential errors in their citations, verify the existence of sources, and prevent accidental hallucinations often generated by Large Language Models (LLMs). We stand firmly against plagiarism and academic dishonesty.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Acceptable Use Policy</h2>
          <ul className="list-disc pl-5 mt-2 space-y-2">
            <li><strong>Verification:</strong> Using the tool to check if the sources in your draft actually exist and are correctly attributed.</li>
            <li><strong>Formatting:</strong> Using the tool to correct citation styles (APA, MLA, etc.) for sources you have already researched.</li>
            <li><strong>Draft Review:</strong> Running your own original work through the tool to identify potential errors before submission.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Prohibited Use</h2>
          <ul className="list-disc pl-5 mt-2 space-y-2">
            <li><strong>Fabrication:</strong> Using the tool to generate lists of sources for papers you have not read or researched.</li>
            <li><strong>Plagiarism:</strong> Using the tool to verify copied text without proper attribution.</li>
            <li><strong>Contract Cheating:</strong> Using the tool to improve the quality of work produced for another person in exchange for compensation.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Statement on AI Hallucinations</h2>
          <p>Users must understand that AI tools can produce "hallucinations"—false information presented as fact. While VeriCite Academic uses cross-verification with real databases (Crossref, Google Search) to minimize this, no automated tool is infallible. The final responsibility for the accuracy of any academic work rests solely with the author.</p>
        </section>

        <section>
            <div className="bg-blue-50 border-l-4 border-blue-600 p-4 mt-8">
                <p className="font-semibold text-blue-900">A Note to Students:</p>
                <p className="text-blue-800 mt-1">Always check your institution's specific guidelines regarding the use of AI tools in coursework. Transparency with your instructors regarding the tools you use is the best policy.</p>
            </div>
        </section>
      </div>
    </div>
  );
};